[package]
name = "omicsops-dto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
hex.workspace = true
omicsops-protocol = { path = "../omicsops-protocol" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid = { workspace = true, features = ["js"] }

[dev-dependencies]
serde_json.workspace = true
